raw_path: "/opt/datasets/outputs/05_2350_to_2670_w_interval_2_voxel_0_2_original.pcd"
octomap_path: ""
pplremover_path: ""
removert_path: ""
erasor_path: ""
erasor2_path: "/opt/datasets/outputs/05_0_frame_2350_to_2670_estimated.pcd"
four_d_mos_path: ""
scan2map_path: ""
