erasor2:
    grid_resolution: 2.0
    egocentric_grid_resolution: 0.6
    range_of_interest: 60.0
    # min_z_voi 와 max_z_voi 는 raw cloud 기준 (ERASOR 1.0과 다름!!!)
    min_z_voi: -4.0
    max_z_voi: 1.5
    min_z_diff_thr: 0.4 # 물체가 존재한다고 가정 할 수있는 최소한의 z 차이
    scan_ratio_threshold: 0.2 # The Larger, the more aggressive!!
    log_odds:
        unknown_prior: -2.0
        informative_prior: 0.5
        initial_prior: 0.3
        increment_gain: 1.0 # Should be larger than one
        increment: 0.3
    prob_region_proposal_thr: 0.8
    kernel_size: 1

    # For checking ground likelihood
    ratio_num_pts: 0.95 # Percentage
    minimum_num_pts: 5

    # For detection moving objects
    moving_object_detection:
        obj_score_soft_thr: 0.8
        obj_score_hard_thr: 20.0
        hard_thr_radius: 20.0

    volumetric_outlier_removal:
        window_size: 1

        dist_thr_gain: 1.732 # The larger, the more aggressive

    viz_flag:
        set_scan_and_pose: false
        set_submap: false
        update: false
        detect: true

