start_frame: 0
end_frame:  12476 #9000
viz_interval: 10
is_large_scale: true

dataprocessor:
    dataset_root: "/kmos_bench/sequences/KAIST05/"
    process_lidar_list: ["Avia", "Ouster", "Velodyne", "Aeva"]
    save_ins_to_LiDAR_root: "/kmos_bench/sequences/KAIST05/ins_to_lidar2"
    saveFormat: "bin"

dataloader:
    run_traj_clustering: true
    dataset_name: "HeLiPR"
    abs_data_dir: "/media/se0yeon00/SY_Other/HeliPR/KAIST05/deskewed_LiDAR3/"
    cloud_dir: ""
    cloud_format: ".bin"
    pose_path: "/kmos_bench/sequences/KAIST05/deskewed_LiDAR"
    sequence: "Merged"
    abs_save_dir: "/kmos_bench/sequences/KAIST05/deskewed_LiDAR"
    instance_seg_method: "hdbscan"

    accum_interval: 1
    voxel_size: 0.4
    map_voxel_size: 0.4

erasor2:
    grid_resolution: 2.0
    egocentric_grid_resolution: 1.0
    range_of_interest: 60.0
    # min_z_voi 와 max_z_voi 는 raw cloud 기준 (ERASOR 1.0과 다름!!!)
    min_z_voi: -3.0
    max_z_voi: 1.4
    min_z_diff_thr: 0.4 # 물체가 존재한다고 가정 할 수있는 최소한의 z 차이
    scan_ratio_threshold: 0.2 # The Larger, the more objects could be candidates
    log_odds:
        increment_gain: 2.0 # Should be larger than one
        increment: 0.05
    region_proposal_thr: 0.8 # probabiliy. 0 ~ 1
    kernel_size: 1

    # For checking ground likelihood
    ratio_num_pts: 0.95 # Percentage
    minimum_num_pts: 5
    minimum_num_per_voxel_: 1

    # For detection moving objects
    moving_object_detection:
        negative_log_odds: -2.0
        obj_score_soft_thr: 1.098
        obj_score_hard_thr: 14.0
        hard_thr_radius: 20.0

    # To manage over-segmented parts
    over_segmentation:
        minimum_area_thr: 56 # [m^2]
        ratio_of_unknown_prior: 0.25

    volumetric_outlier_removal:
        window_size: 1
        use_adaptive_voxel_size: true
        vor_cand_score_thr: 3.0 # Larger than `obj_score_soft_thr` and smaller than `obj_score_hard_thr`
        dist_thr_gain: 2.0 # The larger, the more aggressive

    viz_flag:
        set_scan_and_pose: false
        set_submap: false
        update: false
        detect: false
        over_seg: false

stop_for_each_frame: true

extrinsic:
    robot_body_size: 0.0 # 2.7
    sensor_height: 1.73
    rotation: [ 1, 0, 0,
                0, 1, 0,
                0, 0, 1 ]
    translation: [ 0.0, 0.0, 0.0 ]
