start_frame: 150
end_frame: 250
viz_interval: 10
is_large_scale: true

dataloader:
    dataset_name: "SemanticKITTI"
    abs_data_dir: "/media/shapelim/Elements/SemanticKITTI_w_gt/dataset/sequences"
    cloud_dir: ""
    cloud_format: ""
    pose_path: ""
    sequence: "01"
    abs_save_dir: "/media/shapelim/UX980/erasor_outputs/SemanticKITTI"

    accum_interval: 1
    voxel_size: 0.2
    map_voxel_size: 0.2

erasor2:
    grid_resolution: 2.0
    egocentric_grid_resolution: 0.6
    range_of_interest: 80.0
    # min_z_voi 와 max_z_voi 는 raw cloud 기준 (ERASOR 1.0과 다름!!!)
    min_z_voi: -4.5
    max_z_voi: 1.5
    min_z_diff_thr: 0.4 # 물체가 존재한다고 가정 할 수있는 최소한의 z 차이
    scan_ratio_threshold: 0.2 # The Larger, the more aggressive!!
    log_odds:
        unknown_prior: -2.0
        informative_prior: 0.5
        initial_prior: 0.3
        increment_gain: 1.0 # Should be larger than one
        increment: 0.3
    ground_log_odds_thr: 0.8
    kernel_size: 1

    # For checking ground likelihood
    ratio_num_pts: 0.95 # Percentage
    minimum_num_pts: 5

    # For detection moving objects
    moving_object_detection:
        obj_score_soft_thr: 0.8
        obj_score_hard_thr: 0.8
        hard_thr_radius: 20.0
        xy_size_thr: 20.0 # Set as large as possible! To filter definite static clusters

    volumetric_outlier_removal:
        window_size: 3
        num_closest: 3 # Deprecated
        dist_thr_gain: 1.732 # The larger, the more aggressive

    viz_flag:
        set_scan_and_pose: false
        set_submap: false
        update: false
        detect: true

stop_for_each_frame: true

extrinsic:
    robot_body_size: 2.7
    sensor_height: 1.73
    rotation: [ 1, 0, 0,
                0, 1, 0,
                0, 0, 1 ]
    translation: [ 0.0, 0.0, 0.0 ]
