start_frame: 2350
end_frame: 2670
viz_interval: 10
is_large_scale: true

dataloader:
    dataset_name: "SemanticKITTI"
    abs_data_dir: "/media/shapelim/Elements/SemanticKITTI_w_gt/dataset/sequences"
    cloud_dir: ""
    cloud_format: ""
    pose_path: ""
    sequence: "05"
    abs_save_dir: "/media/shapelim/UX980/erasor_outputs/SemanticKITTI"

    accum_interval: 2
    voxel_size: 0.2
    map_voxel_size: 0.2

erasor2:
    # min_z_voi 와 max_z_voi 는 raw cloud 기준 (ERASOR 1.0과 다름!!!)
    min_z_voi: -4.0
    max_z_voi: 1.5
    th_bin_max_h: 0.2 # [m] 바닥이 0 m라고 가정 (ERASOR 1.0과 같음!!!!)
    scan_ratio_threshold: 0.1 # The Larger, the more aggressive!!
    ground_likelihood:
        increment: 0.3
        decrement: 0.1
    ground_likelihood_thr: 0.5

    minimum_num_pts: 5
    rejection_ratio: 0

    grid_resolution: 1.0
    egocentric_grid_resolution: 0.6
    range_of_interest: 60.0

    viz_flag:
        set_scan_and_pose: false
        set_submap: false
        update: false
        reproject: false

stop_for_each_frame: true

extrinsic:
    robot_body_size: 2.7
    sensor_height: 1.73
    rotation: [ 1, 0, 0,
                0, 1, 0,
                0, 0, 1 ]
    translation: [ 0.0, 0.0, 0.0 ]

