name: erasor2
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.13
  - numpy>=1.18.0
  - matplotlib>=3.3.0
  - scikit-learn>=0.24.0
  - hdbscan>=0.8.28
  - tqdm>=4.62.0
  - tabulate>=0.8.9
  - pip
  - pip:
    - open3d>=0.15.0
    - pypatchworkpp
    - rerun-sdk>=0.21
